# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'whatdog' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Fabric
  pod 'Fabric'
  pod 'Crashlytics'

  # Pods for whatdog
  pod 'TensorFlow-experimental'
end
